// Turns an audit pack into its two formats: an .xlsx workbook and a standalone printable HTML report.
import { fmtStamp, userName } from '../data/logic'
import { rangeLabel, type AuditPack } from '../data/audit'
import type { DbState } from '../data/types'
import { buildXlsx, type Sheet } from './xlsx'

export function auditWorkbook(db: DbState, pack: AuditPack): Uint8Array {
  const summary: Sheet = {
    name: 'Summary',
    columns: ['Field', 'Value'],
    rows: [
      ['Audit pack for', pack.person.name],
      ['Records', rangeLabel(pack.range)],
      ['Generated', fmtStamp(pack.generatedAt)],
      ['Generated by', userName(db, pack.generatedBy)],
      ['Handling', "Contains personal data. Handle under your organisation's data protection policy."],
      ['', ''],
      ...pack.facts,
      ['', ''],
      ...pack.summary.map((s) => [s.label, s.value] as [string, string]),
    ],
  }
  return buildXlsx([summary, ...pack.sections.map((s) => ({ name: s.title, columns: s.columns, rows: s.rows }))])
}

const esc = (v: unknown) => String(v ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')

/** A self-contained HTML document that prints cleanly (and can be saved as PDF from any browser). */
export function auditReportHtml(db: DbState, pack: AuditPack): string {
  const toc = pack.sections.map((s, i) => `<li><a href="#${s.id}">${i + 1}. ${esc(s.title)}</a> <span class="n">${s.rows.length}</span></li>`).join('')
  const sections = pack.sections
    .map(
      (s, i) => `<section id="${s.id}">
  <h2>${i + 1}. ${esc(s.title)} <span class="n">${s.rows.length} ${s.rows.length === 1 ? 'row' : 'rows'}</span></h2>
  <p class="desc">${esc(s.description)}</p>
  ${s.rows.length === 0 ? '<p class="empty">No records.</p>' : `<table><thead><tr>${s.columns.map((c) => `<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${s.rows.map((r) => `<tr>${r.map((c) => `<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
</section>`,
    )
    .join('\n')
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Audit pack · ${esc(pack.person.name)}</title>
<style>
  :root { --ink:#0f172a; --muted:#64748b; --line:#e2e8f0; --brand:#22459f; --bg:#fff; }
  * { box-sizing:border-box }
  body { margin:0; padding:32px 16px; font:13px/1.45 system-ui,-apple-system,"Segoe UI",Roboto,sans-serif; color:var(--ink); background:var(--bg) }
  main { max-width:1100px; margin:0 auto }
  header { border-bottom:3px solid var(--brand); padding-bottom:12px; margin-bottom:18px }
  h1 { font-size:24px; margin:0 0 4px } .kicker { color:var(--brand); font-weight:600; letter-spacing:.06em; text-transform:uppercase; font-size:11px }
  .meta { color:var(--muted) } .warn { margin-top:8px; padding:6px 10px; background:#fff7ed; border:1px solid #fed7aa; border-radius:6px; color:#9a3412; font-size:12px }
  .grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(220px,1fr)); gap:6px 24px; margin:14px 0 }
  .grid div { display:flex; justify-content:space-between; gap:12px; border-bottom:1px dotted var(--line); padding:3px 0 } .grid span:first-child { color:var(--muted) }
  .tiles { display:grid; grid-template-columns:repeat(auto-fit,minmax(130px,1fr)); gap:8px; margin:14px 0 20px }
  .tile { border:1px solid var(--line); border-radius:8px; padding:8px 10px } .tile b { display:block; font-size:18px } .tile span { color:var(--muted); font-size:11px; text-transform:uppercase; letter-spacing:.04em }
  ol.toc { columns:2; padding-left:18px; margin:0 0 24px } ol.toc li { list-style:none; margin:2px 0 } a { color:var(--brand); text-decoration:none }
  .n { color:var(--muted); font-weight:400; font-size:12px }
  section { margin:0 0 26px; break-inside:auto }
  h2 { font-size:16px; margin:0 0 2px; break-after:avoid } .desc { color:var(--muted); margin:0 0 8px } .empty { color:var(--muted); font-style:italic }
  table { width:100%; border-collapse:collapse; font-size:11.5px; font-variant-numeric:tabular-nums }
  th { text-align:left; background:#f1f5f9; font-weight:600; border-bottom:1px solid #cbd5e1 }
  th, td { padding:4px 6px; vertical-align:top; border-bottom:1px solid var(--line) }
  thead { display:table-header-group } tr { break-inside:avoid }
  footer { color:var(--muted); font-size:11px; border-top:1px solid var(--line); padding-top:8px }
  @media print { body { padding:0 } @page { size:A4 landscape; margin:12mm } a { color:inherit } }
</style></head>
<body><main>
<header>
  <div class="kicker">PAT team · PATops audit pack</div>
  <h1>${esc(pack.person.name)}</h1>
  <div class="meta">${esc(rangeLabel(pack.range))} · generated ${esc(fmtStamp(pack.generatedAt))} by ${esc(userName(db, pack.generatedBy))}</div>
  <div class="warn">Contains personal data about staff and students. Handle and store under your organisation's data protection policy.</div>
</header>
<div class="grid">${pack.facts.map(([k, v]) => `<div><span>${esc(k)}</span><span>${esc(v)}</span></div>`).join('')}</div>
<div class="tiles">${pack.summary.map((s) => `<div class="tile"><span>${esc(s.label)}</span><b>${esc(s.value)}</b></div>`).join('')}</div>
<ol class="toc">${toc}</ol>
${sections}
<footer>End of audit pack · ${pack.sections.reduce((n, s) => n + s.rows.length, 0)} records across ${pack.sections.length} sections.</footer>
</main></body></html>`
}
